theme: jekyll-theme-slate
title: Rahim Kurwa
description: My work is broadly focused on the policing of housing. I am writing a book, Indefensible Spaces: Policing and the Remaking of Racial Segregation, that examines policing's role in racial segregation through a case study in Los Angeles` Antelope Valley.
