theme: jekyll-theme-cayman
title: Rahim Kurwa
description: I am a sociologist interested in how policing fits in the catalogue of forces creating and maintaining racial segregation in the United States. My book project, Indefensible Spaces: Policing and the Remaking of Racial Segregation, traces this process as it has played out in Los Angeles northernmost outpost, the Antelope Valley. My other interests are in the family implications of the policing of housing, the history of policing in public housing, and the role of digital platforms like Nextdoor, Ring, and Citizen in contemporary policing.


