theme: jekyll-theme-minimal
title: Rahim Kurwa
description: Department of Criminology, Law, and Justice University of Illinois Chicago 
1007 West Harrison Street, \#4050D Chicago, IL 60607-7104 
rak@uic.edu
