theme: jekyll-theme-minimal
title: Rahim Kurwa
description: My work is broadly focused on the policing of housing. My book project, Indefensible Spaces: Policing and the Remaking of Racial Segregation, explores policing's role in racial segregation by tracing the past century of Black community making and housing struggles in Los Angeles' northernmost outpost, the Antelope Valley.
